
stages:
  - push to GitHub




deploy dev:
  stage: push to GitHub
  image: docker
  script:
    - alpine/git
  environment:
    name: GitHub
    url: https://github.com/jsql-optimization/jsql-laravel
  only:
    refs:
      - master


